version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data/mysql:/var/lib/mysql
    # ports:
    #   - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      UPLOAD_LIMIT: 750M
    ports:
      - 3002:80
    links:
      - db:db

  wordpress:
    image: wordpress:5.8-php7.4
    volumes:
      - ./wp-content:/var/www/html/wp-content
    ports:
      - 3000:80
    links:
      - db:db
    environment:
        WORDPRESS_DEBUG: 'true'
        WORDPRESS_DB_HOST: db
        WORDPRESS_DB_NAME: wordpress
        WORDPRESS_DB_USER: root
        WORDPRESS_DB_PASSWORD: root
        WORDPRESS_CONFIG_EXTRA: |
          define('FS_METHOD','direct');